version: "3.7"
services:
  bot:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on: 
    - clickhouse
    environment: 
    - clickhouse=tcp://clickhouse:9000
    env_file: services.env
    networks: 
    - grafana-networks
  clickhouse:
    build: 
      context: .
      dockerfile: ClickhouseDockerfile
    ports:
    - 8123:8123
    - 9000:9000
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    networks: 
    - grafana-networks
  grafana:
    build: 
      context: grafana
      dockerfile: Dockerfile
    ports:
    - "3000:3000"
    networks: 
    - grafana-networks
networks: 
  grafana-networks: